import { NextResponse } from 'next/server';
import { auth } from '@/lib/auth';
import { db } from '@/lib/db';
import { drafts, threads, posts } from '@/lib/db/schema';
import { eq, and, inArray, desc, gte } from 'drizzle-orm';
import { createLogger } from '@/lib/logger';

const log = createLogger('api:x:engagement');

/**
 * GET /api/x/engagement
 * List engagement opportunities: recent X reply drafts needing response.
 * These are drafts generated by the x-engagement worker when someone
 * replies to the user's tweets.
 */
export async function GET() {
  const session = await auth();
  if (!session?.user?.id) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  // Get recent X posts (last 3 days) to show engagement context
  const lookback = new Date(Date.now() - 3 * 24 * 60 * 60 * 1000);

  const recentPosts = await db
    .select({
      id: posts.id,
      externalId: posts.externalId,
      externalUrl: posts.externalUrl,
      community: posts.community,
      status: posts.status,
      postedAt: posts.postedAt,
    })
    .from(posts)
    .where(
      and(
        eq(posts.userId, session.user.id),
        gte(posts.postedAt, lookback),
      ),
    )
    .orderBy(desc(posts.postedAt))
    .limit(20);

  // Filter to X posts (numeric external IDs)
  const xPosts = recentPosts.filter(
    (p) => p.externalId && /^\d+$/.test(p.externalId),
  );

  // Get pending engagement reply drafts
  const engagementDrafts = await db
    .select({
      id: drafts.id,
      threadId: drafts.threadId,
      replyBody: drafts.replyBody,
      confidenceScore: drafts.confidenceScore,
      status: drafts.status,
      createdAt: drafts.createdAt,
      threadTitle: threads.title,
      threadCommunity: threads.community,
      threadUrl: threads.url,
    })
    .from(drafts)
    .innerJoin(threads, eq(drafts.threadId, threads.id))
    .where(
      and(
        eq(drafts.userId, session.user.id),
        eq(threads.platform, 'x'),
        inArray(drafts.status, ['pending', 'needs_revision']),
        gte(drafts.createdAt, lookback),
      ),
    )
    .orderBy(desc(drafts.createdAt))
    .limit(30);

  return NextResponse.json({
    recentPosts: xPosts,
    engagementDrafts: engagementDrafts.map((d) => ({
      id: d.id,
      replyBody: d.replyBody,
      confidenceScore: d.confidenceScore,
      status: d.status,
      createdAt: d.createdAt,
      thread: {
        title: d.threadTitle,
        community: d.threadCommunity,
        url: d.threadUrl,
      },
    })),
  });
}
