CREATE TABLE IF NOT EXISTS "discovery_configs" (
	"id" text PRIMARY KEY NOT NULL,
	"user_id" text NOT NULL,
	"platform" text DEFAULT 'reddit' NOT NULL,
	"weight_relevance" real DEFAULT 0.3 NOT NULL,
	"weight_intent" real DEFAULT 0.45 NOT NULL,
	"weight_exposure" real DEFAULT 0.1 NOT NULL,
	"weight_freshness" real DEFAULT 0.1 NOT NULL,
	"weight_engagement" real DEFAULT 0.05 NOT NULL,
	"intent_gate" real DEFAULT 0.5 NOT NULL,
	"relevance_gate" real DEFAULT 0.5 NOT NULL,
	"gate_cap" real DEFAULT 0.45 NOT NULL,
	"enqueue_threshold" real DEFAULT 0.7 NOT NULL,
	"custom_pain_phrases" text[] DEFAULT '{}',
	"custom_query_templates" text[] DEFAULT '{}',
	"strategy_rules" text,
	"platform_strategy_override" text,
	"custom_low_relevance_patterns" text,
	"calibration_status" text DEFAULT 'pending' NOT NULL,
	"calibration_round" integer DEFAULT 0 NOT NULL,
	"calibration_precision" real,
	"calibration_log" jsonb,
	"optimization_version" integer DEFAULT 0 NOT NULL,
	"runs_since_optimization" integer DEFAULT 0 NOT NULL,
	"last_optimized_at" timestamp,
	"precision_at_optimization" real,
	"previous_config" jsonb,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "discovery_configs_user_id_platform_unique" UNIQUE("user_id","platform")
);
--> statement-breakpoint
ALTER TABLE "discovery_configs" ADD CONSTRAINT "discovery_configs_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
